export const SAVE_TRANSACTION_INCOME_TYPE = "SAVE_TRANSACTION_INCOME_TYPE";
export const SAVE_TRANSACTION_EXPENSE_TYPE = "SAVE_TRANSACTION_EXPENSE_TYPE";

export const SAVE_EXPENDITURE_TYPE = "SAVE_EXPENDITURE_TYPE";

export const SAVE_USER_INFO = "SAVE_USER_INFO";

export const SAVE_CURRENCY_TYPE = "SAVE_CURRENCY_TYPE";